-- SUPERSEDED — do not run.
--
-- This file combined two independent fixes in one transaction. The Supabase SQL
-- editor runs a pasted script as a single transaction, so one failing statement
-- rolled back the rest, including the grants that actually mattered. Verified after
-- the fact: has_schema_privilege('authenticated','private','USAGE') was still false.
--
-- Split into:
--   0003_grant_private_schema.sql  — the blocking fix; run this
--   0004_revoke_anon_execute.sql   — defence in depth; run after 0003
--
-- Kept as a record of the finding rather than deleted, since 0001 was corrected in
-- place and a fresh install never needs any of these.
